python/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('users.urls')),
    path('npcs/', include('npcs.urls')),
    #
    # # packages
    # url(r'^jsreverse/$', urls_js, name='js_reverse'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python/npcs/urls.py
from django.urls import path

from npcs import views


app_name = 'npcs'
urlpatterns = [
    path('create/', views.create_npc, name='create_npc'),
]

python/users/urls.py
from django.urls import path

from users import views


app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('guest/', views.guest, name='guest'),
    path('logout/', views.user_logout, name='logout'),
]

python/users/models.py
from django.core.mail import send_mail
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone


class UserManager(BaseUserManager):
    def _create_user(self, username, email, password,
                     is_staff, is_superuser, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        now = timezone.now()
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(username=username, email=email,
                          is_staff=is_staff, is_active=True,
                          is_superuser=is_superuser, last_login=now,
                          date_joined=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email, password=None, **extra_fields):
        return self._create_user(username, email, password, False, False,
                                 **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        return self._create_user(username, email, password, True, True,
                                 **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """ An email based user model """

    USERNAME_FIELD = 'email'

    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(_('staff status'), default=False,
                                   help_text=_('Designates whether the user can log into this admin site.'))
    is_active = models.BooleanField(_('active'), default=True,
                                    help_text=_('Designates whether this user should be treated as '
                                    'active. Deselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        return self.username

    def get_username(self):
        return self.username

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Sends an email to this User."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    @property
    def messages(self):
        return {"new": []}

    @property
    def notifications(self):
        return {"new": []}

python/users/forms.py
from django import forms
from django.contrib.auth import authenticate, get_user_model
from django.utils.translation import ugettext_lazy as _

from utils.cleaning import normalise_email

User = get_user_model()


class LoginForm(forms.Form):
    """create login form with placeholders for fields"""

    email = forms.CharField(required=True, label="Email")
    password = forms.CharField(required=True, widget=forms.PasswordInput())

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        if password and email:
            user = authenticate(email=normalise_email(email), password=password)
            if not user:
                raise forms.ValidationError("Login invalid")
        return self.cleaned_data

    def login(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        return user


class RegistrationForm(forms.Form):
    """ User Registration form """

    username = forms.CharField(max_length=30, required=True)
    email = forms.CharField(required=True)
    password = forms.CharField(required=True, widget=forms.PasswordInput())
    password2 = forms.CharField(required=True, label="Confirm password", widget=forms.PasswordInput())

    def clean_username(self):
        """
        Validate for usernames, keep upper/lowercase but compare without them
        """
        username = self.cleaned_data.get('username')
        try:
            User.objects.get(username__iexact=username)
            raise forms.ValidationError(_("This username already exists"))
        except User.DoesNotExist:
            return username

    def clean_email(self):
        """
        Validates that the email address does not exist already, and tests
        against lower cased email address.
        """
        raw_email = self.cleaned_data.get('email')
        email = normalise_email(raw_email)
        try:
            User.objects.get(email__iexact=email)
            raise forms.ValidationError(_("This email already exists"))
        except User.DoesNotExist:
            return email

    def clean(self):
        # validate passwords
        password = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        if password and password2 and password != password2:
            raise forms.ValidationError("Passwords do not match")

        return self.cleaned_data

    def save(self):
        # remove password2
        self.cleaned_data.pop('password2')
        return User.objects.create_user(**self.cleaned_data)

python/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required

from users.forms import RegistrationForm, LoginForm


@login_required
def index(request):
    return render(request, "users/dashboard.html")


@login_required
def user_logout(request):
    logout(request)
    return redirect('users:guest')


def guest(request):
    login_form = LoginForm(data=request.POST or None, prefix="login")
    register_form = RegistrationForm(data=request.POST or None, prefix="register")
    if request.POST:
        import pdb
        pdb.set_trace()
        if login_form.is_valid():
            user = login_form.login()
            if user.is_active:
                login(request, user)
                return redirect('users:index')
            else:
                messages.error(request, 'This account has been deleted.')
                return redirect('users:guest')
        elif register_form.is_valid():
            user = register_form.save()
            # FIXME change to validation email later
            login(request, user)
            return redirect('users:index')

    return render(request, "users/guest.html", {"login_form": login_form, "register_form": register_form})

python/users/templates/users/dashboard.html
{% extends "base.html" %}
{% load compress %}
{% block title %}Dashboard{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Dashboard</h1>
      <p>
        things to put here<br>
        - groups playing near yours<br>
        - npc that had changes since last play session<br>
        - relationship changes<br>
        - messages<br>
      </p>
  </div>
</div>

{% endblock %}

{% block js %}
{% compress js inline %}
<script>

</script>
{% endcompress %}
{% endblock %}

python/users/templates/users/guest.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load compress %}
{% block title %}Guest{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-12">
    <h1 class="h1">Welcome to DnD Social</h1>
  </div>
</div>

<div class="row">
  <div class="col-sm-4" id="loginPanel">
    <div class="card card-accent-primary">
      <div class="card-header">
        Login
      </div>
      <form id="loginForm" action="{% url 'users:guest' %}" method="POST" role="form">
        <div class="card-body">
          {% csrf_token %}
          {% bootstrap_form login_form %}

          <div class="text-right">
            <a href="#">Forgot password?</a>
            <button type="button" class="btn btn-info swap-forms"data-target="registerPanel">Register</button>
            <button type="submit" class="btn btn-warning">Sign in</button>
          </div>
        </div>
      </form>
    </div>
  </div>

  <div class="col-sm-4 hidden" id="registerPanel">
    <div class="card card-accent-primary">
      <div class="card-header">
        Register
      </div>
      <form id="registerForm" action="{% url 'users:guest' %}" method="POST" role="form">
        <div class="card-body">
          {% csrf_token %}
          {% bootstrap_form register_form %}

          <div class="text-right">
            <a href="#" class="swap-forms" data-target="loginPanel">Back to login</a>
            <button type="submit" class="btn btn-info">Register</button>
          </div>
        </div>
      </form>
    </div>
  </div>

  <div class="col-sm-8">
    <p>DnD Social blablabla text</p>
  </div>

</div>
{% endblock %}

{% block js %}
{% compress js inline %}
<script>
// swap between the login and register form
var toggleForms = function(){
  $('#loginPanel').toggleClass('hidden');
  $('#registerPanel').toggleClass('hidden');
};

$('.swap-forms').on('click', function() {
  toggleForms()
});
</script>
{% endcompress %}
{% endblock %}

python/users/templates/users/messages.html
{% load static %}
{% with messages=request.user.messages %}
<li class="dropdown messages-menu">
<a href="#" class="dropdown-toggle" data-toggle="dropdown">
  <i class="fa fa-envelope-o"></i>
  {% if messages.new %}
  <span class="label label-success">{{ messages.new|length }}</span>
  {% endif %}
</a>
<ul class="dropdown-menu">
  {% if messages.new %}
  <li class="header">You have {{ messages.new|length }} messages</li>
  {% endif %}
  <li>
    <ul class="menu">
      {% for notification in messages.new %}
      <li>
        <a href="#">
          <div class="pull-left">
            <img src="{% static 'users/images/avatars/user2-160x160.jpg' %}" class="img-circle"
                 alt="User Image">
          </div>
          <h4>
            Support Team
            <small><i class="fa fa-clock-o"></i> 5 mins</small>
          </h4>
          <p>Why not buy a new awesome theme?</p>
        </a>
      </li>
      {% empty %}
        No new messages
      {% endfor %}
      <!-- end message -->
    </ul>
  </li>
  <li class="footer"><a href="#">See All Messages</a></li>
</ul>
</li>
{% endwith %}

python/users/templates/users/notifications.html
{% with notifications=request.user.notifications %}
<li class="dropdown notifications-menu">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <i class="fa fa-bell-o"></i>
    {% if notifications.new %}
    <span class="label label-warning">{{ notifications.new|length }}</span>
    {% endif %}
  </a>
  <ul class="dropdown-menu">
    {% if notifications.new %}
    <li class="header">You have {{ notifications.new|length }} new notifications</li>
    {% endif %}
    <li>
      <ul class="menu">
        {% for notification in notifications.new %}
        <li>
          <a href="#">
            <i class="fa fa-users text-aqua"></i> 5 new members joined today
          </a>
        </li>
        {% empty %}
        <li>
          No new notifications
        </li>
        {% endfor %}
      </ul>
    </li>
    <li class="footer"><a href="#">View all</a></li>
  </ul>
</li>
{% endwith %}

python/users/templates/users/tasks.html
<li class="dropdown tasks-menu">
<a href="#" class="dropdown-toggle" data-toggle="dropdown">
  <i class="fa fa-flag-o"></i>
  <span class="label label-danger">9</span>
</a>
<ul class="dropdown-menu">
  <li class="header">You have 9 tasks</li>
  <li>
    <!-- inner menu: contains the actual data -->
    <ul class="menu">
      <li><!-- Task item -->
        <a href="#">
          <h3>
            Design some buttons
            <small class="pull-right">20%</small>
          </h3>
          <div class="progress xs">
            <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar"
                 aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
              <span class="sr-only">20% Complete</span>
            </div>
          </div>
        </a>
      </li>
      <!-- end task item -->
    </ul>
  </li>
  <li class="footer">
    <a href="#">View all tasks</a>
  </li>
</ul>
</li>

python/users/templates/users/user_menu.html
{% load static %}
<li class="dropdown user user-menu">
<a href="#" class="dropdown-toggle" data-toggle="dropdown">
  <img src="{% static 'users/images/avatars/user2-160x160.jpg' %}" class="user-image" alt="User Image">
  <span class="hidden-xs">{{ request.user.username }}</span>
</a>
<ul class="dropdown-menu">
  <li class="user-header">
    <img src="{% static 'users/images/avatars/user2-160x160.jpg' %}" class="img-circle" alt="User Image">

    <p>
      {{ request.user.username }}
      <small>{{ request.user.date_joined|date }}</small>
    </p>
  </li>
  {% comment %}
  <li class="user-body">
    <div class="row">
      <div class="col-xs-4 text-center">
        <a href="#">Followers</a>
      </div>
      <div class="col-xs-4 text-center">
        <a href="#">Sales</a>
      </div>
      <div class="col-xs-4 text-center">
        <a href="#">Friends</a>
      </div>
    </div>
  </li>
  {% endcomment %}
  <li class="user-footer">
    <div class="pull-left">
      <a href="#" class="btn btn-default btn-flat">Profile</a>
    </div>
    <div class="pull-right">
      <a href="{% url 'users:logout' %}" class="btn btn-default btn-flat">Sign out</a>
    </div>
  </li>
</ul>
</li>